spring:
  application:
    name: kycarrots
    messages:
      basename: messages
      encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/planfshop
    username: planfshop
    password: planf1122!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      #show_sql: true
      format_sql: true
  mail:
    host: mw-002.cafe24.com
    port: 587
    username: admin@planf.shop
    password: amway1122!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

#MyBatis MyBatisConfig 로 교체함 나중에 다시 할것
#mybatis:
  #type-aliases-package: com.whomade.kycarrots.entity

  #mapper-locations: classpath:mapper/**/*.xml

  #configuration:
    #map-underscore-to-camel-case: true
    #jdbcTypeForNull: NULL


logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.whomade.kycarrots: trace