server:
  port: 9000
spring:
  application:
    name: kycarrots
    messages:
      basename: messages
      encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kycarrotsdb
    username: kycarrots
    password: kycarrots
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      #show_sql: true
      format_sql: true
  mail:
    host: mw-002.cafe24.com
    port: 587
    username: admin@planf.shop
    password: amway1122!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

#MyBatis MyBatisConfig 로 교체함 나중에 다시 할것
#mybatis:
  #type-aliases-package: com.whomade.kycarrots.entity

  #mapper-locations: classpath:mapper/**/*.xml

  #configuration:
    #map-underscore-to-camel-case: true
    #jdbcTypeForNull: NULL


logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.whomade.kycarrots: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

spring.servlet.multipart:
  max-file-size: 10MB        # 파일 하나 최대
  max-request-size: 50MB     # 요청 전체 최대(파일 여러 개 합)
  enabled: true

sendgrid:
  api-key: ${SENDGRID_API_KEY}        # OS 환경변수에서 주입
  from-address: ${SENDGRID_FROM:seo3997@gmail.com}

file:
  # 총 업로드 용량(요청 내 모든 파일 합계)
  max-size-total: 50MB
  # 개별 파일 최대 용량
  max-size-each: 10MB
  product:
    upload-dir: /var/www/uploads/product
    public-url: http://52.231.229.156:9000/common/img/product
    resource-path: file:/var/www/uploads/product/
  board:
    upload-dir: /var/www/uploads/board
    public-url: http://52.231.229.156:9000/common/img/board
    resource-path: file:/var/www/uploads/board/